### ISSUE TITLE
Your stuff needs some resprites

### ISSUE THREAD

**Issue by DatOnePlayer** [MoTRona/Colloseus-Mod#1]
It copies several content from another mods

The mending dome is from HolyHades

The huge to gigantic walls are from Mesokrix

**Comment by DatOnePlayer** [comment]
@MoTRona

**Comment by MoTRona** [comment]
Okay, I agree with the walls, but not with the regenerating dome. I just
took an overdrive dome and repainted it.
The walls will be redrawn.

If you find more bugs or flaws, tell me about it. Thx

пт, 4 дек. 2020 г., 12:19 Yudhis Striker <notifications@github.com>:

**Comment by DatOnePlayer** [comment]
At least make the mending Dome a little different
![Screenshot_20201204-184028_Mindustry](https://user-images.githubusercontent.com/61370548/101159702-638edf00-3660-11eb-983a-c9ac549154a8.jpg)

Left is your mod, right is HolyHades Vanilla Enhanced mod

**Comment by DatOnePlayer** [comment]
@MoTRona
