### ISSUE TITLE
The Unit Upgrader doesnt let units in

### ISSUE THREAD

**Issue by NoCreative01** [MoTRona/Colloseus-Mod#13]
hi, i was really hyped to get new strong units. i really like the design from the mod. but somehow the "upgrader" doesnt work.
problems: - it shows the resources not correctly, when i put ressources in they doesnt show when are enough are in.
                 - after a time it shows enough items but the unit cant come in. it only blocks them.
                 maybe you can response to this. i really want this mod. it is a beautiful mod.

**Comment by TagGamer555** [comment]
same issue.
