### ISSUE TITLE
Game crashes when Leviathan is spawned, game is running on android 6.0

### ISSUE THREAD

**Issue by Stavinair** [MoTRona/Colloseus-Mod#2]
Mindustry has crashed. How unfortunate.
Version: release build 120.3
OS: Linux x32
Java Version: 0
Java Architecture: null
1 Mods: collos:1.0.0

> Evaluator: 'Java class "arc.util.Time" has no public instance field or method named "__noSuchMethod__". (leviathan#470)'
DefaultErrorReporter.runtimeError: 68
Context.reportRuntimeError: 830
Context.reportRuntimeError: 876
Context.reportRuntimeError2: 850
JavaMembers.reportMemberNotFound: 809
NativeJavaClass.get: 91
ScriptableObject.getProperty: 2182
ScriptRuntime.getPropFunctionAndThisHelper: 2344
ScriptRuntime.getPropFunctionAndThis: 2333
OptRuntime.callProp0: 69
leviathan_30._c_anonymous_6: 470
leviathan_30.call: -1
JavaAdapter.doCall: 572
JavaAdapter.callMethod: 554
adapter50.drawBlackHole: -1
MemberBox.invoke: 105
NativeJavaMethod.call: 205
OptRuntime.call1: 23
leviathan_30._c_anonymous_5: 460
leviathan_30.call: -1
ContextFactory.doTopCall: 346
ScriptRuntime.doTopCall: 3303
leviathan_30.call: -1
JavaAdapter.doCall: 572
JavaAdapter.callMethod: 554
adapter50.draw: -1
UnitWaterMove.draw: 587
-$$Lambda$ifrumY3k6WQ-gZrF-jKr17eciiM.get: -1
EntityGroup.lambda$draw$0$EntityGroup: 84
-$$Lambda$EntityGroup$7yx2cm6It40ZgVo--jbAiYvhzn8.get: -1
EntityGroup.each: 68
EntityGroup.draw: 81
Renderer.draw: 258
Renderer.update: 92
ApplicationCore.update: 36
ClientLauncher.update: 153
AndroidGraphics.onDrawFrame: 424
GLSurfaceView$GLThread.guardedRun: 1535
GLSurfaceView$GLThread.run: 1240

**Comment by MoTRona** [comment]
I know what the problem is, just wait for the new version.

сб, 5 дек. 2020 г., 20:15 Stavinair <notifications@github.com>:
