### ISSUE TITLE
What happened to the dead and corrupted terrain blocks and tiles?

### ISSUE THREAD

**Issue by Duvent-mindustry** [MoTRona/Colloseus-Mod#20]
please help
![image](https://user-images.githubusercontent.com/73276338/127775388-e99536ff-076a-45ff-96d2-9781cc665fb6.png)

**Comment by Duvent-mindustry** [comment]
Turrets and Multiple other blocks also dont appear in the Menu

**Comment by MoTRona** [comment]
I can't be sure that the bug is in Colloseus Mod, because you have other mods enabled

**Comment by Duvent-mindustry** [comment]
i have removed every mod and texture packs and its still broken, im on v7 if you didnt already know
![image](https://user-images.githubusercontent.com/73276338/127795422-29514183-51b8-4fda-ae59-33cc7da61598.png)

**Comment by MoTRona** [comment]
Mod doesn't work on v7. Disable it
