### ISSUE TITLE
translations and ui issues

### ISSUE THREAD

**Issue by Stavinair** [MoTRona/Colloseus-Mod#3]
The UI scaling for the block that let's you spawn in units, alter weather, etc, is cut off on my screen. Also, is there any plans to release a version with english translatons? 
![Screenshot_2020-12-09-09-06-13](https://user-images.githubusercontent.com/57328437/101647365-3f375780-39fe-11eb-8788-d12087622aac.png)
![Uploading Screenshot_2020-12-09-09-06-46.png…](

**Comment by MoTRona** [comment]
Different devices have different resolution, which means the command block needs to be fully reworked. English translation will be soon.
