### ISSUE TITLE
Duplicated items on tech tree making it way too big

### ISSUE THREAD

**Issue by joey7022** [MoTRona/Colloseus-Mod#4]
![2020 12 20-19 16](https://user-images.githubusercontent.com/76416987/102735819-3d23a180-42f8-11eb-9284-eb4f3a0b884b.png)
For example, the lead wall has 2 copies extremely spaced apart that makes the tech tree extremely big

**Comment by MoTRona** [comment]
Fixed func.js. Please check it.

**Comment by joey7022** [comment]
> Fixed func.js. Please check it.

that fixed it! thanks
