### ISSUE TITLE
Unit self-destroys after spawn

### ISSUE THREAD

**Issue by TagGamer555** [MoTRona/Colloseus-Mod#6]
Unit self-destroys after spawn by using unit command block(i forgot the real name)
![image](https://user-images.githubusercontent.com/69044271/103674287-a01b6680-4f8f-11eb-8634-3462909cdff9.png)

**Comment by TagGamer555** [comment]
I don't really know how to use them

**Comment by MoTRona** [comment]
1. To spawn the units so that they were alive, you need to shift their point spavna.

**Comment by MoTRona** [comment]
1. To spawn units you need shift their spawn point coordinates.
2. Modification development forever stopped.
3. I want cake.

**Comment by SorterBoi** [comment]
🍰
cake
